Repository aws-samples/pcluster-manager, pull requests merged in 2022-11, with the labels that each got.

#349 Disable cluster edit button in case ParallelCluster API full version does not match cluster full version
  frontend/src/old-pages/Clusters/Actions.tsx
Labels: bug, release-include

#351 ADR: automating release changelog creation
  decisions/20221107-adopt-github-labels-to-allow-automating-release-changelog-creation.md
Labels: ADR

#350 Add GitHub release config for changelog automation
  .github/release.yml
Labels: release-exclude

#352 Filter out clusters in configuration source 'From Cluster' dropdown in case they do not match up to the minor version of PC
  frontend/locales/en/strings.json
  frontend/src/old-pages/Configure/Source.tsx
Labels: bug, release-include

#355 Match tags when authenticating to AWS in a release
  infrastructure/github-env-setup-prod.yml
Labels: release-exclude

#358 Fix Logs and Stack Events not being searchable
  frontend/src/old-pages/Clusters/Logs.tsx
  frontend/src/old-pages/Clusters/StackEvents.tsx
Labels: release-include

#370 Added frontend logger implementation to push logs to CloudWatch through the backend
  frontend/src/http/__tests__/executeRequest.test.ts
  frontend/src/http/executeRequest.tsx
  frontend/src/logger/ConsoleLogger.ts
  frontend/src/logger/ILogger.ts
  frontend/src/logger/LoggerProvider.tsx
  frontend/src/logger/RemoteLogger.ts
  frontend/src/logger/__tests__/logger.test.ts
  frontend/src/model.tsx
  frontend/src/pages/_app.tsx
Labels: release:improvement

#375 Remove user group from authorization model
  api/PclusterApiHandler.py
  api/tests/test_exception_handlers.py
  app.py
  frontend/src/model.tsx
  frontend/src/old-pages/Users/Users.tsx
Labels: release:breaking-change

#371 Introduce ErrorBoundary component which serves as a global exception handler for the frontend
  frontend/locales/en/strings.json
  frontend/src/components/ErrorBoundary.tsx
  frontend/src/components/__tests__/ErrorBoundary.test.tsx
  frontend/src/pages/_app.tsx
Labels: release:improvement
