Repository aws-samples/pcluster-manager, pull requests merged in 2022-12, with the labels that each got.

#383 Added security headers to improve application security posture
  api/security/__init__.py
  api/security/headers.py
  api/tests/conftest.py
  api/tests/test_add_response_headers.py
  api/tests/test_build_flask_app.py
  api/utils.py
Labels: release:improvement

#385 Enable access logs on the API Gateway
  infrastructure/pcluster-manager.yaml
Labels: release:breaking-change

#421 Safely import ComputeResources config created with single instance type
  e2e/configs/environment.ts
  e2e/configs/login.ts
  e2e/fixtures/wizard.template.yaml
  e2e/specs/wizard.spec.ts
  e2e/specs/wizard.template.spec.ts
  e2e/test-utils/login.ts
  frontend/src/old-pages/Configure/Queues/Queues.tsx
  frontend/src/old-pages/Configure/Queues/__tests__/mapComputeResources.test.ts
  frontend/src/old-pages/Configure/Queues/queues.mapper.ts
  frontend/src/old-pages/Configure/util.tsx
Labels: release:bugfix

#441 Handle buffered log entries on the backend
  api/logging/__init__.py
  api/logging/logger.py
  api/pcm_globals.py
  api/tests/test_logger.py
  api/tests/test_push_log.py
  app.py
  frontend/src/logger/ConsoleLogger.ts
  frontend/src/logger/ILogger.ts
  frontend/src/logger/RemoteLogger.ts
  frontend/src/logger/__tests__/logger.test.ts
Labels: release:improvement

#443 Avoid boto3 exception details leakage
  api/exception/handlers.py
  api/tests/exceptions/test_exception_handlers.py
Labels: release:improvement

#447 Buffer logs sent from the frontend
  frontend/src/logger/RemoteLogger.ts
  frontend/src/logger/__tests__/logger.test.ts
Labels: release:improvement

#445 Added Cognito logout implementation
  api/PclusterApiHandler.py
  api/tests/test_logout.py
Labels: release:improvement
